### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by voanhkha** [geek-ai/MAgent#59]
Dear MAgent developpers,
I am mainly working on Windows 10. May I ask is there a possible way to run magent on Windows? 
This would be extremely appreciated.

Kind regards,
Kha.

**Comment by merrymercy** [comment]
For the cpp core engine and python interface, if i remember correctly, we don't use linux-specific feature.
For the render, cc @Kipsora

**Comment by Kipsora** [comment]
Currently we do not have Windows supported. But you can help yourself by using WSL to build the renderer, the dependencies of which can be easily resolved by `apt install`. For the MAgent library, you can build the MAgent library using `MinGW`. There may be some codes that are not incompatible with Windows but most of them can be resolve them easily. 

I am going to close this issue since it is not what we support. If you have any questions on building MAgent on Windows, please reopen the issue.
